export interface University {
  id: string;
  name: string;
  shortName: string;
  conference: string;
  lmsProvider: 'canvas' | 'blackboard' | 'moodle' | 'brightspace';
  lmsLoginUrl: string;
  logoUrl: string;
}

// List of NCAA Division 1 universities with "Demo University" at top, followed by all universities starting with "University"
export const universities: University[] = [
  // Demo University stays at the top
  {
    id: 'demo-university',
    name: 'Demo University',
    shortName: 'Demo U',
    conference: 'Demo Conference',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://demo.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  // Universities starting with "University" in alphabetical order
  {
    id: 'university-akron',
    name: 'University of Akron',
    shortName: 'Akron',
    conference: 'MAC',
    lmsProvider: 'brightspace',
    lmsLoginUrl: 'https://uakron.brightspace.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-alabama',
    name: 'University of Alabama',
    shortName: 'Alabama',
    conference: 'SEC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://ualearn.blackboard.com/ultra/institution-page',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-alabama-birmingham',
    name: 'University of Alabama at Birmingham',
    shortName: 'UAB',
    conference: 'AAC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uab.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-alabama-huntsville',
    name: 'University of Alabama in Huntsville',
    shortName: 'UAH',
    conference: 'ASUN',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uah.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-albany',
    name: 'University at Albany',
    shortName: 'Albany',
    conference: 'America East',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://blackboard.albany.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-arizona',
    name: 'University of Arizona',
    shortName: 'Arizona',
    conference: 'Big 12',
    lmsProvider: 'brightspace',
    lmsLoginUrl: 'https://d2l.arizona.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-arkansas',
    name: 'University of Arkansas',
    shortName: 'Arkansas',
    conference: 'SEC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://learn.uark.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-arkansas-little-rock',
    name: 'University of Arkansas at Little Rock',
    shortName: 'UALR',
    conference: 'Ohio Valley',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://ualr.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-arkansas-pine-bluff',
    name: 'University of Arkansas at Pine Bluff',
    shortName: 'UAPB',
    conference: 'SWAC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://uapb.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-buffalo',
    name: 'University at Buffalo',
    shortName: 'Buffalo',
    conference: 'MAC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://ublearns.buffalo.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-california-berkeley',
    name: 'University of California, Berkeley',
    shortName: 'UC Berkeley',
    conference: 'Pac-12',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://bcourses.berkeley.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-california-davis',
    name: 'University of California, Davis',
    shortName: 'UC Davis',
    conference: 'Big West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.ucdavis.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-california-irvine',
    name: 'University of California, Irvine',
    shortName: 'UC Irvine',
    conference: 'Big West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.eee.uci.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-california-los-angeles',
    name: 'University of California, Los Angeles',
    shortName: 'UCLA',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://ccle.ucla.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-california-riverside',
    name: 'University of California, Riverside',
    shortName: 'UC Riverside',
    conference: 'Big West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.ucr.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-california-san-diego',
    name: 'University of California, San Diego',
    shortName: 'UC San Diego',
    conference: 'Big West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.ucsd.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-california-santa-barbara',
    name: 'University of California, Santa Barbara',
    shortName: 'UC Santa Barbara',
    conference: 'Big West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.ucsb.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-central-arkansas',
    name: 'University of Central Arkansas',
    shortName: 'Central Arkansas',
    conference: 'ASUN',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://uca.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-central-florida',
    name: 'University of Central Florida',
    shortName: 'UCF',
    conference: 'Big 12',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://webcourses.ucf.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-chicago',
    name: 'University of Chicago',
    shortName: 'Chicago',
    conference: 'UAA',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.uchicago.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-cincinnati',
    name: 'University of Cincinnati',
    shortName: 'Cincinnati',
    conference: 'Big 12',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uc.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-colorado-boulder',
    name: 'University of Colorado Boulder',
    shortName: 'Colorado',
    conference: 'Big 12',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.colorado.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-connecticut',
    name: 'University of Connecticut',
    shortName: 'UConn',
    conference: 'Big East',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://lms.uconn.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-dayton',
    name: 'University of Dayton',
    shortName: 'Dayton',
    conference: 'A-10',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://udayton.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-delaware',
    name: 'University of Delaware',
    shortName: 'Delaware',
    conference: 'CAA',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://udel.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-denver',
    name: 'University of Denver',
    shortName: 'Denver',
    conference: 'Summit League',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.du.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-detroit-mercy',
    name: 'University of Detroit Mercy',
    shortName: 'Detroit Mercy',
    conference: 'Horizon League',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://udmercy.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-evansville',
    name: 'University of Evansville',
    shortName: 'Evansville',
    conference: 'Missouri Valley',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://evansville.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-florida',
    name: 'University of Florida',
    shortName: 'Florida',
    conference: 'SEC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://ufl.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-georgia',
    name: 'University of Georgia',
    shortName: 'Georgia',
    conference: 'SEC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uga.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-hartford',
    name: 'University of Hartford',
    shortName: 'Hartford',
    conference: 'America East',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://hartford.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-hawaii-manoa',
    name: 'University of Hawaii at Manoa',
    shortName: 'Hawaii',
    conference: 'Mountain West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://laulima.hawaii.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-houston',
    name: 'University of Houston',
    shortName: 'Houston',
    conference: 'Big 12',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://uh.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-idaho',
    name: 'University of Idaho',
    shortName: 'Idaho',
    conference: 'Big Sky',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uidaho.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-illinois-chicago',
    name: 'University of Illinois Chicago',
    shortName: 'UIC',
    conference: 'Missouri Valley',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://uic.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-illinois-urbana-champaign',
    name: 'University of Illinois Urbana-Champaign',
    shortName: 'Illinois',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.illinois.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-indiana',
    name: 'University of Indiana',
    shortName: 'Indiana',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://iu.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-iowa',
    name: 'University of Iowa',
    shortName: 'Iowa',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uiowa.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-kansas',
    name: 'University of Kansas',
    shortName: 'Kansas',
    conference: 'Big 12',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://ku.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-kentucky',
    name: 'University of Kentucky',
    shortName: 'Kentucky',
    conference: 'SEC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uk.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-louisiana-lafayette',
    name: 'University of Louisiana at Lafayette',
    shortName: 'Louisiana',
    conference: 'Sun Belt',
    lmsProvider: 'moodle',
    lmsLoginUrl: 'https://moodle.louisiana.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-louisiana-monroe',
    name: 'University of Louisiana at Monroe',
    shortName: 'ULM',
    conference: 'Sun Belt',
    lmsProvider: 'moodle',
    lmsLoginUrl: 'https://ulm.moodle.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-louisville',
    name: 'University of Louisville',
    shortName: 'Louisville',
    conference: 'ACC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://louisville.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-maine',
    name: 'University of Maine',
    shortName: 'Maine',
    conference: 'America East',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://umaine.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-maryland',
    name: 'University of Maryland',
    shortName: 'Maryland',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://umd.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-maryland-baltimore-county',
    name: 'University of Maryland, Baltimore County',
    shortName: 'UMBC',
    conference: 'America East',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://umbc.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-maryland-eastern-shore',
    name: 'University of Maryland Eastern Shore',
    shortName: 'UMES',
    conference: 'MEAC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://umes.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-massachusetts',
    name: 'University of Massachusetts',
    shortName: 'UMass',
    conference: 'A-10',
    lmsProvider: 'moodle',
    lmsLoginUrl: 'https://moodle.umass.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-massachusetts-lowell',
    name: 'University of Massachusetts Lowell',
    shortName: 'UMass Lowell',
    conference: 'America East',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://uml.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-memphis',
    name: 'University of Memphis',
    shortName: 'Memphis',
    conference: 'AAC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://memphis.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-miami',
    name: 'University of Miami',
    shortName: 'Miami',
    conference: 'ACC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://miami.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-michigan',
    name: 'University of Michigan',
    shortName: 'Michigan',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://umich.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-minnesota',
    name: 'University of Minnesota',
    shortName: 'Minnesota',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.umn.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-mississippi',
    name: 'University of Mississippi',
    shortName: 'Ole Miss',
    conference: 'SEC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://blackboard.olemiss.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-missouri',
    name: 'University of Missouri',
    shortName: 'Missouri',
    conference: 'SEC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://missouri.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-missouri-kansas-city',
    name: 'University of Missouri-Kansas City',
    shortName: 'UMKC',
    conference: 'Summit League',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://umkc.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-montana',
    name: 'University of Montana',
    shortName: 'Montana',
    conference: 'Big Sky',
    lmsProvider: 'moodle',
    lmsLoginUrl: 'https://umonline.umt.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-nebraska',
    name: 'University of Nebraska',
    shortName: 'Nebraska',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.unl.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-nebraska-omaha',
    name: 'University of Nebraska Omaha',
    shortName: 'UNO',
    conference: 'Summit League',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://unomaha.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-nevada-las-vegas',
    name: 'University of Nevada, Las Vegas',
    shortName: 'UNLV',
    conference: 'Mountain West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://webcampus.unlv.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-nevada-reno',
    name: 'University of Nevada, Reno',
    shortName: 'Nevada',
    conference: 'Mountain West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://webcampus.unr.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-new-hampshire',
    name: 'University of New Hampshire',
    shortName: 'New Hampshire',
    conference: 'America East',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://unh.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-new-mexico',
    name: 'University of New Mexico',
    shortName: 'New Mexico',
    conference: 'Mountain West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://learn.unm.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-new-mexico-state',
    name: 'University of New Mexico State',
    shortName: 'New Mexico State',
    conference: 'Conference USA',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://nmsu.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-north-carolina',
    name: 'University of North Carolina',
    shortName: 'UNC',
    conference: 'ACC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://unc.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-north-carolina-asheville',
    name: 'University of North Carolina Asheville',
    shortName: 'UNC Asheville',
    conference: 'Big South',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://unca.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-north-carolina-charlotte',
    name: 'University of North Carolina at Charlotte',
    shortName: 'Charlotte',
    conference: 'AAC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uncc.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-north-carolina-greensboro',
    name: 'University of North Carolina at Greensboro',
    shortName: 'UNC Greensboro',
    conference: 'SoCon',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uncg.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-north-carolina-wilmington',
    name: 'University of North Carolina Wilmington',
    shortName: 'UNC Wilmington',
    conference: 'CAA',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uncw.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-north-dakota',
    name: 'University of North Dakota',
    shortName: 'North Dakota',
    conference: 'Summit League',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://und.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-north-florida',
    name: 'University of North Florida',
    shortName: 'North Florida',
    conference: 'ASUN',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://unf.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-north-texas',
    name: 'University of North Texas',
    shortName: 'North Texas',
    conference: 'AAC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://unt.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-northern-colorado',
    name: 'University of Northern Colorado',
    shortName: 'Northern Colorado',
    conference: 'Big Sky',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://unco.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-northern-iowa',
    name: 'University of Northern Iowa',
    shortName: 'Northern Iowa',
    conference: 'Missouri Valley',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uni.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-notre-dame',
    name: 'University of Notre Dame',
    shortName: 'Notre Dame',
    conference: 'ACC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.nd.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-oklahoma',
    name: 'University of Oklahoma',
    shortName: 'Oklahoma',
    conference: 'SEC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.ou.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-oregon',
    name: 'University of Oregon',
    shortName: 'Oregon',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.uoregon.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-pennsylvania',
    name: 'University of Pennsylvania',
    shortName: 'Penn',
    conference: 'Ivy League',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.upenn.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-pittsburgh',
    name: 'University of Pittsburgh',
    shortName: 'Pittsburgh',
    conference: 'ACC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.pitt.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-portland',
    name: 'University of Portland',
    shortName: 'Portland',
    conference: 'WCC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://up.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-rhode-island',
    name: 'University of Rhode Island',
    shortName: 'Rhode Island',
    conference: 'A-10',
    lmsProvider: 'brightspace',
    lmsLoginUrl: 'https://brightspace.uri.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-richmond',
    name: 'University of Richmond',
    shortName: 'Richmond',
    conference: 'A-10',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://richmond.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-san-diego',
    name: 'University of San Diego',
    shortName: 'San Diego',
    conference: 'WCC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://sandiego.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-san-francisco',
    name: 'University of San Francisco',
    shortName: 'San Francisco',
    conference: 'WCC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://usfca.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-south-alabama',
    name: 'University of South Alabama',
    shortName: 'South Alabama',
    conference: 'Sun Belt',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://southalabama.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-south-carolina',
    name: 'University of South Carolina',
    shortName: 'South Carolina',
    conference: 'SEC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://blackboard.sc.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-south-carolina-upstate',
    name: 'University of South Carolina Upstate',
    shortName: 'USC Upstate',
    conference: 'Big South',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://uscupstate.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-south-dakota',
    name: 'University of South Dakota',
    shortName: 'South Dakota',
    conference: 'Summit League',
    lmsProvider: 'brightspace',
    lmsLoginUrl: 'https://usd.brightspace.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-south-florida',
    name: 'University of South Florida',
    shortName: 'South Florida',
    conference: 'AAC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://usflearn.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-southern-california',
    name: 'University of Southern California',
    shortName: 'USC',
    conference: 'Big Ten',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://blackboard.usc.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-southern-mississippi',
    name: 'University of Southern Mississippi',
    shortName: 'Southern Miss',
    conference: 'Sun Belt',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://usm.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-st-thomas',
    name: 'University of St. Thomas',
    shortName: 'St. Thomas',
    conference: 'Summit League',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://stthomas.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-tennessee',
    name: 'University of Tennessee',
    shortName: 'Tennessee',
    conference: 'SEC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://utk.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-tennessee-chattanooga',
    name: 'University of Tennessee at Chattanooga',
    shortName: 'Chattanooga',
    conference: 'SoCon',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://utc.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-tennessee-martin',
    name: 'University of Tennessee at Martin',
    shortName: 'UT Martin',
    conference: 'Ohio Valley',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://utm.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-texas',
    name: 'University of Texas',
    shortName: 'Texas',
    conference: 'SEC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://utexas.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-texas-arlington',
    name: 'University of Texas at Arlington',
    shortName: 'UT Arlington',
    conference: 'WAC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uta.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-texas-el-paso',
    name: 'University of Texas at El Paso',
    shortName: 'UTEP',
    conference: 'Conference USA',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://utep.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-texas-rio-grande-valley',
    name: 'University of Texas Rio Grande Valley',
    shortName: 'UTRGV',
    conference: 'WAC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://utrgv.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-texas-san-antonio',
    name: 'University of Texas at San Antonio',
    shortName: 'UTSA',
    conference: 'AAC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://utsa.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-toledo',
    name: 'University of Toledo',
    shortName: 'Toledo',
    conference: 'MAC',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://utoledo.blackboard.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-tulsa',
    name: 'University of Tulsa',
    shortName: 'Tulsa',
    conference: 'AAC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://utulsa.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-utah',
    name: 'University of Utah',
    shortName: 'Utah',
    conference: 'Big 12',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://utah.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-vermont',
    name: 'University of Vermont',
    shortName: 'Vermont',
    conference: 'America East',
    lmsProvider: 'blackboard',
    lmsLoginUrl: 'https://bb.uvm.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-virginia',
    name: 'University of Virginia',
    shortName: 'Virginia',
    conference: 'ACC',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.its.virginia.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-washington',
    name: 'University of Washington',
    shortName: 'Washington',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.uw.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-west-virginia',
    name: 'University of West Virginia',
    shortName: 'West Virginia',
    conference: 'Big 12',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://wvu.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-wisconsin-green-bay',
    name: 'University of Wisconsin-Green Bay',
    shortName: 'Green Bay',
    conference: 'Horizon League',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uwgb.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-wisconsin-madison',
    name: 'University of Wisconsin-Madison',
    shortName: 'Wisconsin',
    conference: 'Big Ten',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://canvas.wisc.edu/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-wisconsin-milwaukee',
    name: 'University of Wisconsin-Milwaukee',
    shortName: 'Milwaukee',
    conference: 'Horizon League',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uwm.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'university-wyoming',
    name: 'University of Wyoming',
    shortName: 'Wyoming',
    conference: 'Mountain West',
    lmsProvider: 'canvas',
    lmsLoginUrl: 'https://uwyo.instructure.com/',
    logoUrl: 'https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
];